### PR TITLE
Update with master

### PR DESCRIPTION
**Pull request by raytlin**
@cwshevlin @chadjaros 

updated our fork with master. this solves the google dependency issues with this pod. unfortunately, after i made these changes, i found out that we have more dependency issues with our google cloud storage APIs. We really won't be able to fix all of the pod issues until we update the google APIs. however, since we are moving to to WS media upload, we might as well wait until that's done and just use WS. after we implement WS media upload on ios we can point to this branch for pdf upload and that should finally solve our pod problems. i hope.

### CODE REVIEW

**Comment by chadjaros** [comment]
So do you need this PR reviewed, or is it not on the path to being merged?

**Comment by raytlin** [comment]
@chadjaros It will need to be merged eventutally but we probably won't want to implement until WS media upload is finished.

**Comment by cwshevlin** [comment]
LGTM

**Comment by timoman** [comment]
@raytlin is this closeable?

**Pull request closed without merging**
