### PR TITLE
Dependency injection to allow for customization of the GTMOAuth2ViewC…

### PR DESCRIPTION
**Pull request by timoman**
…ontroller

Ok, take two on this.
The new approach is to style the Google Drive viewer with customizations to HSGoogleDrivePicker only, without touching oauth2.

tbh I think dependency injection here is a good idea, but might need more cleanup before it could be good for a pull request back to the original repo.

### CODE REVIEW

**Comment by timoman** [comment]
Note to self: have to move the 0.1.5-ck tag to the latest commit after merging this

**Comment by cwshevlin** [comment]
Can we test this before the other PR is merged without physically replacing the old files with these files?

**Comment by timoman** [comment]
I tested by replacing the old files. I think you might be able to change the podfile to point to the commit on my branch

**Comment by timoman** [comment]
This worked for me for testing:

```
pod 'HSGoogleDrivePicker', :git => 'https://github.com/timoman/HSGoogleDrivePicker.git', :commit => '3063a7c'
```

**Comment by peterfdo** [comment]
:shipit:

**Comment by cwshevlin** [comment]
:ship:

**Pull request merged**
